version: "3"
services:
  slack-emoji-notification:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: slack-emoji-watcher-image 
    container_name: slack-emoji-watcher-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
